# Remplace par les valeurs affichées sur ton écran SonarCloud
sonar.projectKey=wiamelkhoumari01_project-artista
sonar.organization=wiamelkhoumari01
sonar.host.url=https://sonarcloud.io

# Configuration des sources (garde ce qu'on a fait)
sonar.sources=app, resources/js
sonar.sourceEncoding=UTF-8
sonar.exclusions=vendor/**, node_modules/**, public/**